sudo: false
git:
  submodules: false
branches:
  only:
  - master
before_script: make init
script: make build
env:
  global:
    secure: a9/KDTPolVoGxkNYfOoo0fXxronBvcVQ/reAeEAEplagM6fw1vX6GpMm2pBYNQz/ZkaKQZY2fXWZg8i9gMe/+idEiOCbytcq0/uqKD2ZUoGfJH5Zu+KHOxFSMJJrGL87zMeumPEXuK3CPKZYYtZUPbqbMfhvDLIQUknAcEKn07QzhOFtMcxePxMwUN55fbvBZ3YZI+7auk23yRiUpIMNOiptj/RFjK9iFFQamHhngG+KLwg/HV0Kiao106Qu+SfPIJO/oWlXDJWuBwDGiqXhk+M9ltvt8KjM+hodDZ5WbpH1wlyC7hf2Dnx757DPHJDetag66t9OStIJs9TGKPkRs411Mmi3AmUWGScSMI4G4rdMrPeDvGveBdIXmO8aKYZQ62m2gwEH341wnENFiupLdSEpfv+PTKNqaRdYqKZYwQU3ZSTmTav/O6iAgapyhKJGcm++uoRudMfSIM1N6jOKhZ5udP6NoVOCz2CUQAVIkaryGO+iMdG1+reTc3f06i3VdPHgnNOC229kg4QbfUwKDC2ahiXIaHrZFuDtBqkT7bJFfDT5RXJGSGwcqZh8Udev8dTAu0nBN4C60TVieEFSjLgCB0LacuELTmzSFlJvrtETbY+KbgViMzwij/EKJ9ZFDQwsqMLL06E7GKDNm5FoLup//Eh4BCYBgr8zNBB4Npg=
