sudo: false
git:
  submodules: false
branches:
  only:
    - master
before_script: make init
script: make build
env:
  global:
    secure: 'hNtqABJHnTjcKXz0RXtc1C2dQpLvpN4vifDuCJsvEsS/ridq59dUxVogS7m5WccKkIvRlDIlR5Y6x2ZKeK9AyTO1FOgxvgMsCWvcTnYNJ8pdOarMsMNz7lVWb6X03Fq3K2U3lx8Hl2EjFJSwnm3quDmdyYIfNl0q4zz0GJ56mqeSzRJWxgIfITo/7aVJE98CMktqS+z9sSZSGz18pHKEmvxehLJGG2VpzHGEbjX3yPUlB3cjJB8ZQY7qHOMTiHCQ0m+BXYY19AvNuqQXv1nssAPQOtrkdb2NQ9vIeODe7l+wMwsH9hnDzyc9WW/ib2RIAEdj6GwrznC+2ueNCptfYRiVa1gAoTKqAjx0qtJ3ykJal4l0WJ0BQ4ELzT3TWufpjwPuqYW8mV72mEdYZArQh2HT+0SF8haUYUsLY+JziFzlJOiYOImLDpu2QgqzSc9ye6d3E1o2nzY5KlAEnvx4S1BAec/X9sQhuw4TNV55WjobBnEM71djI4+13nvU2/VVHwDV2Plp8OAsHM7UCPC1BkoWvHUzev150/3dZ4I2NEuya1An08PUt0dkBw/h9NLDuvT7DmVQVNJg6ki12enL8K8rzaqT1VrUnSjXvXAOcgZpYuMI1S2tuueuYdBPgcHfxCFsNeVodj38PzBGJje10HYUEgugL7SoQ6rKlKAtV50='
