sudo: false
git:
  submodules: false
branches:
  only:
  - master
before_script: make init
script: make build
env:
  global:
    secure: fmzN0RWvcpE5kDaui05BnWSpQCblURzopI+ufYL63JVQ6fjLR945z+IqcXdxR0h3wmlc+WDPdpq/UG/X0XEp05CGhCh5AYTy5iXcP+yafZnc5f2/WfZLxSgevWYhKlSKlh57hwlN5Cbcw/J98iik679r4pzgoN9oQXWNkliGKLs7p3jUTS5Mv9ASr6zyg9ScHCS5HH+/E1PKDITMB141yTOJJ51DdbGwuhJQm7yklGBisrIad9tqyblVIAfak4EJ1NxwWaudfrq8lA28ln45D7HeWAYUjnCg6/NIZWugBZvsiEefSyBfmxWSd3W+fmMKzyfAVUCJM13ZH2zuikUP/MFi/AauFD3AV7WKiyDl5YuI0BIjyCz+Vte2soMvwcq6AVkbS7rORJs0PDLMXm+uH8hjUV7uEL45BuVUXcRuELzjjwMtPkKhUflFm+pV+l6Abbazlg0AM/v1GwN3td1YSj5D9sdQrxzqxAQ9WbJF/R8Zd9+eqgTWUJFMoz+sTEn+kM18lPFvwpNRVUrR7JqvrLPr2RT1e/fA8FrMVTUy/bb5BXbfWARy8hmOxFWn/xj3LNyAKCnTbyz+eBl+jdG2dnuaCmVG0JbVJs2OSuWqmh4RI/zXmFW32/twcK2jvtLRHrsoU8bvwPLNA3cH0JNQaCWJCUYr3RWnYyJ1htfQ7EU=
