sudo: false
git:
  submodules: false
branches:
  only:
  - master
before_script: make init
script: make build
env:
  global:
    secure: mw7/aS2lnGb4j7IPOAzwceyTWySSA2ujWz9y0RCPyOSb4IGCPEeHB9MP9CMfN9cteEjneBldC+lPOFzwljLuuosS2lfZKf4ggvQRlpjB+BWEDMzxx94Yc9av0gl62mcNl7ZhRNbAiFw9jVu+KaBqkX8yiq9bJ1GvYvaTUOcG07EuKwx+kHa6vvh27Jio0ijcxba0W3abOqvHOc005+U0awPyCM1lA9+KPBmrV704IHi5ABUCRQyfIko3kSVZArtmjxxNmgdWCO1SLjUl1sU4IpNyMl5DYw1Dck2+Hn4BWgH16Uyuvnwr4Bv2GzGoexVY6lVh7t8zdaRc+SgtspB6aAZgY4I49/fv7Z7LrCFSQUKfNgpkaogP0tDtvdvsctYTd9hV1RclcEJ8e4aJ7NsTsYqHWg0t7sObubfKxvwrKzlybNBaQB0kldroWRhLcvJ81XB4HYhM2LAaN/QoKtJ2mEfLJW47iztOha9AoyGNGF2OIjDKw8wS4q/1pZtXYDjN04lO2uJ3Sgcv3F8XnAyfeI54sBFmZAhycmXrCx5pwP2i+9MDTU1wbCDvm89l5XrdaBdlypo9tHuq6/39Ze6I1MT+jmPKAb4i+P/iGE7gWOXh37H3L/Q4FvnEJPnRBdAhxJwtfItdlitdHnU4XSg24kQUaO7U5LXOVqEZe733C4c=
